services:
  - type: web
    name: telegram-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    runtime: python
    pythonVersion: 3.10
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OPENROUTER_KEY
        sync: false
